"""Dia 4: caja (metodo_pago, turno, movimiento, arqueo)

Revision ID: 02a90f0f7c8c
Revises: 4a874a42b4e9
Create Date: 2026-09-17 21:26:29.679649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a90f0f7c8c'
down_revision = '4a874a42b4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('es_efectivo', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turno_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fondo_inicial', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estadoturno'), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arqueo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('efectivo_contado', sa.Integer(), nullable=False),
    sa.Column('desglose', sa.JSON(), nullable=True),
    sa.Column('diferencia', sa.Integer(), nullable=False),
    sa.Column('motivo_diferencia', sa.Text(), nullable=True),
    sa.Column('diferencia_confirmada', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_caja_id')
    )
    op.create_table('movimiento_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', 'VENTA', name='tipomovimientocaja'), nullable=False),
    sa.Column('categoria', sa.Enum('PROVEEDOR', 'GASTO', 'RETIRO_DUENO', 'VUELTO', 'OTRO', name='categoriamovimientocaja'), nullable=True),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_caja_turno_caja_id'), ['turno_caja_id'], unique=False)

    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movimiento_caja_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_movimiento_inventario_movimiento_caja',
            'movimiento_caja', ['movimiento_caja_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimiento_inventario_movimiento_caja', type_='foreignkey')
        batch_op.drop_column('movimiento_caja_id')

    with op.batch_alter_table('movimiento_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_caja_turno_caja_id'))

    op.drop_table('movimiento_caja')
    op.drop_table('arqueo')
    op.drop_table('turno_caja')
    op.drop_table('metodo_pago')
    # ### end Alembic commands ###
