"""Dia 2: cliente, proveedor, insumo, producto, producto_insumo

Revision ID: 2def4e5f9df4
Revises: 26f3bc25170e
Create Date: 2026-09-17 21:14:12.532445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2def4e5f9df4'
down_revision = '26f3bc25170e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_telefono'), ['telefono'], unique=True)

    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('margen_objetivo', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=50), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insumo_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('producto_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'insumo_id', name='uq_producto_insumo')
    )
    with op.batch_alter_table('producto_insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_insumo_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_insumo_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_insumo_producto_id'))
        batch_op.drop_index(batch_op.f('ix_producto_insumo_insumo_id'))

    op.drop_table('producto_insumo')
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insumo_proveedor_id'))

    op.drop_table('insumo')
    op.drop_table('proveedor')
    op.drop_table('producto')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_telefono'))

    op.drop_table('cliente')
    # ### end Alembic commands ###
