"""Dia 5: pedido y pedido_detalle (+ movimiento_inventario.pedido_id)

Revision ID: 35e5cfdf3c34
Revises: 02a90f0f7c8c
Create Date: 2026-09-17 21:59:16.587009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e5cfdf3c34'
down_revision = '02a90f0f7c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('origen', sa.Enum('MOSTRADOR', 'WHATSAPP', 'PEDIDOSYA', 'RAPPI', 'OTRO', name='origenpedido'), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('pago_procesado_externo', sa.Boolean(), nullable=False),
    sa.Column('tipo_entrega', sa.Enum('RETIRO', 'DELIVERY', 'MOZO', name='tipoentrega'), nullable=False),
    sa.Column('cadete_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'EN_PREPARACION', 'LISTO', 'ENTREGADO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cadete_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origen', 'id_externo', name='uq_pedido_origen_externo')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_numero'), ['numero'], unique=False)

    op.create_table('pedido_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_detalle_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_detalle_producto_id'), ['producto_id'], unique=False)

    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_movimiento_inventario_pedido', 'pedido', ['pedido_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimiento_inventario_pedido', type_='foreignkey')
        batch_op.drop_column('pedido_id')

    with op.batch_alter_table('pedido_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_detalle_producto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_detalle_pedido_id'))

    op.drop_table('pedido_detalle')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_numero'))

    op.drop_table('pedido')
    # ### end Alembic commands ###
