"""Dia 3: lote, conteo y movimiento_inventario

Revision ID: 4a874a42b4e9
Revises: 2def4e5f9df4
Create Date: 2026-09-17 21:18:48.653912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a874a42b4e9'
down_revision = '2def4e5f9df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_sistema', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_contada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conteo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conteo_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lote_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('conteo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('CARGA', 'AJUSTE', 'MERMA', name='tipomovimientoinventario'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conteo_id'], ['conteo.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_inventario_insumo_id'), ['insumo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_inventario_insumo_id'))

    op.drop_table('movimiento_inventario')
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lote_insumo_id'))

    op.drop_table('lote')
    with op.batch_alter_table('conteo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conteo_insumo_id'))

    op.drop_table('conteo')
    # ### end Alembic commands ###
