"""Promocion eliminada (eliminar fake que oculta)

Revision ID: 71a1e58c9c56
Revises: 77e1ee26650e
Create Date: 2026-09-22 13:07:39.945685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a1e58c9c56'
down_revision = '77e1ee26650e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promocion', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'eliminada', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promocion', schema=None) as batch_op:
        batch_op.drop_column('eliminada')

    # ### end Alembic commands ###
