"""Proveedor descripcion y ubicacion

Revision ID: 77e1ee26650e
Revises: c10228343f17
Create Date: 2026-09-21 14:33:16.539431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e1ee26650e'
down_revision = 'c10228343f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('ubicacion')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
