"""Producto.descripcion (carta HUMOS)

Revision ID: c10228343f17
Revises: f1d6672141f3
Create Date: 2026-09-17 22:20:29.351947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10228343f17'
down_revision = 'f1d6672141f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
