"""Dia 6: promociones, notificaciones y descuento de promocion en pedido

Revision ID: f1d6672141f3
Revises: 35e5cfdf3c34
Create Date: 2026-09-17 22:07:54.787214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d6672141f3'
down_revision = '35e5cfdf3c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_descuento', sa.Enum('PORCENTAJE', 'MONTO_FIJO', 'DOS_POR_UNO', name='tipodescuento'), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('aplicacion', sa.Enum('AUTOMATICA', 'MANUAL', name='aplicacionpromocion'), nullable=False),
    sa.Column('vigencia_desde', sa.DateTime(), nullable=False),
    sa.Column('vigencia_hasta', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('STOCK_BAJO', 'POR_VENCER', 'BAJO_MARGEN', name='tiponotificacion'), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('descartada', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocion_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocion_id', 'producto_id', name='uq_promocion_producto')
    )
    with op.batch_alter_table('promocion_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocion_producto_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocion_producto_promocion_id'), ['promocion_id'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento_promocion', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('promocion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_pedido_promocion', 'promocion', ['promocion_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_promocion', type_='foreignkey')
        batch_op.drop_column('promocion_id')
        batch_op.drop_column('descuento_promocion')

    with op.batch_alter_table('promocion_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocion_producto_promocion_id'))
        batch_op.drop_index(batch_op.f('ix_promocion_producto_producto_id'))

    op.drop_table('promocion_producto')
    op.drop_table('notificacion')
    op.drop_table('promocion')
    # ### end Alembic commands ###
